// Created with Corsair v1.0.4
#ifndef __REGS_GPIO_H
#define __REGS_GPIO_H

#define __I  volatile const // 'read only' permissions
#define __O  volatile       // 'write only' permissions
#define __IO volatile       // 'read / write' permissions


#ifdef __cplusplus
#include <cstdint>
extern "C" {
#else
#include <stdint.h>
#endif

#define GPIO_BASE_ADDR 0x40000000

// GPIO_IO - GPIO Read/Write Register
#define GPIO_GPIO_IO_ADDR 0x0
#define GPIO_GPIO_IO_RESET 0x0
typedef struct {
    uint32_t GPIO_0 : 1; // GPIO0
    uint32_t GPIO_1 : 1; // GPIO1
    uint32_t GPIO_2 : 1; // GPIO2
    uint32_t GPIO_3 : 1; // GPIO3
    uint32_t GPIO_4 : 1; // GPIO4
    uint32_t GPIO_5 : 1; // GPIO5
    uint32_t GPIO_6 : 1; // GPIO6
    uint32_t GPIO_7 : 1; // GPIO7
    uint32_t GPIO_8 : 1; // GPIO8
    uint32_t GPIO_9 : 1; // GPIO9
    uint32_t GPIO_10 : 1; // GPIO10
    uint32_t GPIO_11 : 1; // GPIO11
    uint32_t GPIO_12 : 1; // GPIO12
    uint32_t GPIO_13 : 1; // GPIO13
    uint32_t GPIO_14 : 1; // GPIO14
    uint32_t GPIO_15 : 1; // GPIO15
    uint32_t : 16; // reserved
} gpio_gpio_io_t;

// GPIO_IO.GPIO_0 - GPIO0
#define GPIO_GPIO_IO_GPIO_0_WIDTH 1
#define GPIO_GPIO_IO_GPIO_0_LSB 0
#define GPIO_GPIO_IO_GPIO_0_MASK 0x1
#define GPIO_GPIO_IO_GPIO_0_RESET 0x0

// GPIO_IO.GPIO_1 - GPIO1
#define GPIO_GPIO_IO_GPIO_1_WIDTH 1
#define GPIO_GPIO_IO_GPIO_1_LSB 1
#define GPIO_GPIO_IO_GPIO_1_MASK 0x2
#define GPIO_GPIO_IO_GPIO_1_RESET 0x0

// GPIO_IO.GPIO_2 - GPIO2
#define GPIO_GPIO_IO_GPIO_2_WIDTH 1
#define GPIO_GPIO_IO_GPIO_2_LSB 2
#define GPIO_GPIO_IO_GPIO_2_MASK 0x4
#define GPIO_GPIO_IO_GPIO_2_RESET 0x0

// GPIO_IO.GPIO_3 - GPIO3
#define GPIO_GPIO_IO_GPIO_3_WIDTH 1
#define GPIO_GPIO_IO_GPIO_3_LSB 3
#define GPIO_GPIO_IO_GPIO_3_MASK 0x8
#define GPIO_GPIO_IO_GPIO_3_RESET 0x0

// GPIO_IO.GPIO_4 - GPIO4
#define GPIO_GPIO_IO_GPIO_4_WIDTH 1
#define GPIO_GPIO_IO_GPIO_4_LSB 4
#define GPIO_GPIO_IO_GPIO_4_MASK 0x10
#define GPIO_GPIO_IO_GPIO_4_RESET 0x0

// GPIO_IO.GPIO_5 - GPIO5
#define GPIO_GPIO_IO_GPIO_5_WIDTH 1
#define GPIO_GPIO_IO_GPIO_5_LSB 5
#define GPIO_GPIO_IO_GPIO_5_MASK 0x20
#define GPIO_GPIO_IO_GPIO_5_RESET 0x0

// GPIO_IO.GPIO_6 - GPIO6
#define GPIO_GPIO_IO_GPIO_6_WIDTH 1
#define GPIO_GPIO_IO_GPIO_6_LSB 6
#define GPIO_GPIO_IO_GPIO_6_MASK 0x40
#define GPIO_GPIO_IO_GPIO_6_RESET 0x0

// GPIO_IO.GPIO_7 - GPIO7
#define GPIO_GPIO_IO_GPIO_7_WIDTH 1
#define GPIO_GPIO_IO_GPIO_7_LSB 7
#define GPIO_GPIO_IO_GPIO_7_MASK 0x80
#define GPIO_GPIO_IO_GPIO_7_RESET 0x0

// GPIO_IO.GPIO_8 - GPIO8
#define GPIO_GPIO_IO_GPIO_8_WIDTH 1
#define GPIO_GPIO_IO_GPIO_8_LSB 8
#define GPIO_GPIO_IO_GPIO_8_MASK 0x100
#define GPIO_GPIO_IO_GPIO_8_RESET 0x0

// GPIO_IO.GPIO_9 - GPIO9
#define GPIO_GPIO_IO_GPIO_9_WIDTH 1
#define GPIO_GPIO_IO_GPIO_9_LSB 9
#define GPIO_GPIO_IO_GPIO_9_MASK 0x200
#define GPIO_GPIO_IO_GPIO_9_RESET 0x0

// GPIO_IO.GPIO_10 - GPIO10
#define GPIO_GPIO_IO_GPIO_10_WIDTH 1
#define GPIO_GPIO_IO_GPIO_10_LSB 10
#define GPIO_GPIO_IO_GPIO_10_MASK 0x400
#define GPIO_GPIO_IO_GPIO_10_RESET 0x0

// GPIO_IO.GPIO_11 - GPIO11
#define GPIO_GPIO_IO_GPIO_11_WIDTH 1
#define GPIO_GPIO_IO_GPIO_11_LSB 11
#define GPIO_GPIO_IO_GPIO_11_MASK 0x800
#define GPIO_GPIO_IO_GPIO_11_RESET 0x0

// GPIO_IO.GPIO_12 - GPIO12
#define GPIO_GPIO_IO_GPIO_12_WIDTH 1
#define GPIO_GPIO_IO_GPIO_12_LSB 12
#define GPIO_GPIO_IO_GPIO_12_MASK 0x1000
#define GPIO_GPIO_IO_GPIO_12_RESET 0x0

// GPIO_IO.GPIO_13 - GPIO13
#define GPIO_GPIO_IO_GPIO_13_WIDTH 1
#define GPIO_GPIO_IO_GPIO_13_LSB 13
#define GPIO_GPIO_IO_GPIO_13_MASK 0x2000
#define GPIO_GPIO_IO_GPIO_13_RESET 0x0

// GPIO_IO.GPIO_14 - GPIO14
#define GPIO_GPIO_IO_GPIO_14_WIDTH 1
#define GPIO_GPIO_IO_GPIO_14_LSB 14
#define GPIO_GPIO_IO_GPIO_14_MASK 0x4000
#define GPIO_GPIO_IO_GPIO_14_RESET 0x0

// GPIO_IO.GPIO_15 - GPIO15
#define GPIO_GPIO_IO_GPIO_15_WIDTH 1
#define GPIO_GPIO_IO_GPIO_15_LSB 15
#define GPIO_GPIO_IO_GPIO_15_MASK 0x8000
#define GPIO_GPIO_IO_GPIO_15_RESET 0x0

// GPIO_config - GPIO config Register 0 output, 1 input
#define GPIO_GPIO_CONFIG_ADDR 0x4
#define GPIO_GPIO_CONFIG_RESET 0x0
typedef struct {
    uint32_t GPIO_0CONFIG : 1; // GPIO0_config
    uint32_t GPIO_1CONFIG : 1; // GPIO1_config
    uint32_t GPIO_2CONFIG : 1; // GPIO2_config
    uint32_t GPIO_3CONFIG : 1; // GPIO3_config
    uint32_t GPIO_4CONFIG : 1; // GPIO4_config
    uint32_t GPIO_5CONFIG : 1; // GPIO5_config
    uint32_t GPIO_6CONFIG : 1; // GPIO6_config
    uint32_t GPIO_7CONFIG : 1; // GPIO7_config
    uint32_t GPIO_8CONFIG : 1; // GPIO8_config
    uint32_t GPIO_9CONFIG : 1; // GPIO9_config
    uint32_t GPIO_10CONFIG : 1; // GPIO10_config
    uint32_t GPIO_11CONFIG : 1; // GPIO11_config
    uint32_t GPIO_12CONFIG : 1; // GPIO12_config
    uint32_t GPIO_13CONFIG : 1; // GPIO13_config
    uint32_t GPIO_14CONFIG : 1; // GPIO14_config
    uint32_t GPIO_15CONFIG : 1; // GPIO15_config
    uint32_t : 16; // reserved
} gpio_gpio_config_t;

// GPIO_config.GPIO_0config - GPIO0_config
#define GPIO_GPIO_CONFIG_GPIO_0CONFIG_WIDTH 1
#define GPIO_GPIO_CONFIG_GPIO_0CONFIG_LSB 0
#define GPIO_GPIO_CONFIG_GPIO_0CONFIG_MASK 0x1
#define GPIO_GPIO_CONFIG_GPIO_0CONFIG_RESET 0x0

// GPIO_config.GPIO_1config - GPIO1_config
#define GPIO_GPIO_CONFIG_GPIO_1CONFIG_WIDTH 1
#define GPIO_GPIO_CONFIG_GPIO_1CONFIG_LSB 1
#define GPIO_GPIO_CONFIG_GPIO_1CONFIG_MASK 0x2
#define GPIO_GPIO_CONFIG_GPIO_1CONFIG_RESET 0x0

// GPIO_config.GPIO_2config - GPIO2_config
#define GPIO_GPIO_CONFIG_GPIO_2CONFIG_WIDTH 1
#define GPIO_GPIO_CONFIG_GPIO_2CONFIG_LSB 2
#define GPIO_GPIO_CONFIG_GPIO_2CONFIG_MASK 0x4
#define GPIO_GPIO_CONFIG_GPIO_2CONFIG_RESET 0x0

// GPIO_config.GPIO_3config - GPIO3_config
#define GPIO_GPIO_CONFIG_GPIO_3CONFIG_WIDTH 1
#define GPIO_GPIO_CONFIG_GPIO_3CONFIG_LSB 3
#define GPIO_GPIO_CONFIG_GPIO_3CONFIG_MASK 0x8
#define GPIO_GPIO_CONFIG_GPIO_3CONFIG_RESET 0x0

// GPIO_config.GPIO_4config - GPIO4_config
#define GPIO_GPIO_CONFIG_GPIO_4CONFIG_WIDTH 1
#define GPIO_GPIO_CONFIG_GPIO_4CONFIG_LSB 4
#define GPIO_GPIO_CONFIG_GPIO_4CONFIG_MASK 0x10
#define GPIO_GPIO_CONFIG_GPIO_4CONFIG_RESET 0x0

// GPIO_config.GPIO_5config - GPIO5_config
#define GPIO_GPIO_CONFIG_GPIO_5CONFIG_WIDTH 1
#define GPIO_GPIO_CONFIG_GPIO_5CONFIG_LSB 5
#define GPIO_GPIO_CONFIG_GPIO_5CONFIG_MASK 0x20
#define GPIO_GPIO_CONFIG_GPIO_5CONFIG_RESET 0x0

// GPIO_config.GPIO_6config - GPIO6_config
#define GPIO_GPIO_CONFIG_GPIO_6CONFIG_WIDTH 1
#define GPIO_GPIO_CONFIG_GPIO_6CONFIG_LSB 6
#define GPIO_GPIO_CONFIG_GPIO_6CONFIG_MASK 0x40
#define GPIO_GPIO_CONFIG_GPIO_6CONFIG_RESET 0x0

// GPIO_config.GPIO_7config - GPIO7_config
#define GPIO_GPIO_CONFIG_GPIO_7CONFIG_WIDTH 1
#define GPIO_GPIO_CONFIG_GPIO_7CONFIG_LSB 7
#define GPIO_GPIO_CONFIG_GPIO_7CONFIG_MASK 0x80
#define GPIO_GPIO_CONFIG_GPIO_7CONFIG_RESET 0x0

// GPIO_config.GPIO_8config - GPIO8_config
#define GPIO_GPIO_CONFIG_GPIO_8CONFIG_WIDTH 1
#define GPIO_GPIO_CONFIG_GPIO_8CONFIG_LSB 8
#define GPIO_GPIO_CONFIG_GPIO_8CONFIG_MASK 0x100
#define GPIO_GPIO_CONFIG_GPIO_8CONFIG_RESET 0x0

// GPIO_config.GPIO_9config - GPIO9_config
#define GPIO_GPIO_CONFIG_GPIO_9CONFIG_WIDTH 1
#define GPIO_GPIO_CONFIG_GPIO_9CONFIG_LSB 9
#define GPIO_GPIO_CONFIG_GPIO_9CONFIG_MASK 0x200
#define GPIO_GPIO_CONFIG_GPIO_9CONFIG_RESET 0x0

// GPIO_config.GPIO_10config - GPIO10_config
#define GPIO_GPIO_CONFIG_GPIO_10CONFIG_WIDTH 1
#define GPIO_GPIO_CONFIG_GPIO_10CONFIG_LSB 10
#define GPIO_GPIO_CONFIG_GPIO_10CONFIG_MASK 0x400
#define GPIO_GPIO_CONFIG_GPIO_10CONFIG_RESET 0x0

// GPIO_config.GPIO_11config - GPIO11_config
#define GPIO_GPIO_CONFIG_GPIO_11CONFIG_WIDTH 1
#define GPIO_GPIO_CONFIG_GPIO_11CONFIG_LSB 11
#define GPIO_GPIO_CONFIG_GPIO_11CONFIG_MASK 0x800
#define GPIO_GPIO_CONFIG_GPIO_11CONFIG_RESET 0x0

// GPIO_config.GPIO_12config - GPIO12_config
#define GPIO_GPIO_CONFIG_GPIO_12CONFIG_WIDTH 1
#define GPIO_GPIO_CONFIG_GPIO_12CONFIG_LSB 12
#define GPIO_GPIO_CONFIG_GPIO_12CONFIG_MASK 0x1000
#define GPIO_GPIO_CONFIG_GPIO_12CONFIG_RESET 0x0

// GPIO_config.GPIO_13config - GPIO13_config
#define GPIO_GPIO_CONFIG_GPIO_13CONFIG_WIDTH 1
#define GPIO_GPIO_CONFIG_GPIO_13CONFIG_LSB 13
#define GPIO_GPIO_CONFIG_GPIO_13CONFIG_MASK 0x2000
#define GPIO_GPIO_CONFIG_GPIO_13CONFIG_RESET 0x0

// GPIO_config.GPIO_14config - GPIO14_config
#define GPIO_GPIO_CONFIG_GPIO_14CONFIG_WIDTH 1
#define GPIO_GPIO_CONFIG_GPIO_14CONFIG_LSB 14
#define GPIO_GPIO_CONFIG_GPIO_14CONFIG_MASK 0x4000
#define GPIO_GPIO_CONFIG_GPIO_14CONFIG_RESET 0x0

// GPIO_config.GPIO_15config - GPIO15_config
#define GPIO_GPIO_CONFIG_GPIO_15CONFIG_WIDTH 1
#define GPIO_GPIO_CONFIG_GPIO_15CONFIG_LSB 15
#define GPIO_GPIO_CONFIG_GPIO_15CONFIG_MASK 0x8000
#define GPIO_GPIO_CONFIG_GPIO_15CONFIG_RESET 0x0


// Register map structure
typedef struct {
    union {
        __IO uint32_t GPIO_IO; // GPIO Read/Write Register
        __IO gpio_gpio_io_t GPIO_IO_bf; // Bit access for GPIO_IO register
    };
    union {
        __IO uint32_t GPIO_CONFIG; // GPIO config Register 0 output, 1 input
        __IO gpio_gpio_config_t GPIO_CONFIG_bf; // Bit access for GPIO_CONFIG register
    };
} gpio_t;

#define GPIO ((gpio_t*)(GPIO_BASE_ADDR))

#ifdef __cplusplus
}
#endif

#endif /* __REGS_GPIO_H */